### ISSUE TITLE
question ? answer me please 

### ISSUE THREAD

**Issue by chim1999** [dimitreOliveira/APTOS2019BlindnessDetection#1]
which algorithm you have used for diabetic retinopathy? which one is the best ? ( efficient net , ...)

**Comment by dimitreOliveira** [comment]
Hello @chim1999 , sorry for the long delay, for some reason I forgot to mark "Watch" on my own repository.
You can find my best [solution here](https://github.com/dimitreOliveira/APTOS2019BlindnessDetection/tree/master/Best%20solution%20(Bronze%20medal%20-%20163rd%20place), there you wee see everything that I have used, together with a nice description of the solution, but in terms of best model architecture, for me was EfficientNetB5
